/**
 *
 * $Id$
 */
package de.fzi.srp.core.model.markovmodel.samplemodel.validation;

import de.fzi.srp.core.model.markovmodel.markoventity.Action;
import de.fzi.srp.core.model.markovmodel.markoventity.Observation;
import de.fzi.srp.core.model.markovmodel.markoventity.Reward;
import de.fzi.srp.core.model.markovmodel.markoventity.State;

/**
 * A sample validator interface for {@link de.fzi.srp.core.model.markovmodel.samplemodel.Sample}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SampleValidator {
	boolean validate();

	boolean validateReward(Reward value);

	boolean validateAction(Action value);

	boolean validatePointInTime(int value);

	boolean validateCurrent(State value);

	boolean validateNext(State value);

	boolean validateObservation(Observation<?> value);
}
