/**
 *
 * $Id$
 */
package de.fzi.srp.core.model.markovmodel.samplemodel.validation;

import de.fzi.srp.core.model.markovmodel.samplemodel.Trajectory;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.fzi.srp.core.model.markovmodel.samplemodel.SampleModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SampleModelValidator {
	boolean validate();

	boolean validateTrajectories(EList<Trajectory> value);
}
