/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.kmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class KmodelUiModule extends AbstractKmodelUiModule {

	public KmodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
