/*
 * generated by Xtext 2.29.0
 */
package org.palladiosimulator.simexp.dsl.smodel.ui.wizard;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "org.palladiosimulator.simexp.dsl.smodel.ui.wizard.messages"; //$NON-NLS-1$
	
	public static String SModelFile_Label;
	public static String SModelFile_Description;
	
	static {
	// initialize resource bundle
	NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}
	
	private Messages() {
	}
}
