/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.smodel;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SmodelStandaloneSetup extends SmodelStandaloneSetupGenerated {

    public static void doSetup() {
        new SmodelStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
