/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.smodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension
 * registry.
 */
public class SmodelRuntimeModule extends AbstractSmodelRuntimeModule {
}
