/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.kmodel.ide;


/**
 * Use this class to register ide components.
 */
public class KmodelIdeModule extends AbstractKmodelIdeModule {
}
