/**
 *
 * $Id$
 */
package de.fzi.srp.core.model.markovmodel.markoventity.validation;

import de.fzi.srp.core.model.markovmodel.markoventity.Action;
import de.fzi.srp.core.model.markovmodel.markoventity.Observation;
import de.fzi.srp.core.model.markovmodel.markoventity.Reward;
import de.fzi.srp.core.model.markovmodel.markoventity.State;
import de.fzi.srp.core.model.markovmodel.markoventity.Transition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.fzi.srp.core.model.markovmodel.markoventity.MarkovModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MarkovModelValidator {
	boolean validate();

	boolean validateTransitions(EList<Transition> value);

	boolean validateStateSpace(EList<State> value);

	boolean validateReward(EList<Reward> value);

	boolean validateActions(EList<Action> value);

	boolean validateObservations(EList<Observation<?>> value);
}
