/**
 *
 * $Id$
 */
package de.fzi.srp.core.model.markovmodel.markoventity.validation;

import de.fzi.srp.core.model.markovmodel.markoventity.Action;
import de.fzi.srp.core.model.markovmodel.markoventity.State;

/**
 * A sample validator interface for {@link de.fzi.srp.core.model.markovmodel.markoventity.Transition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransitionValidator {
	boolean validate();

	boolean validateSource(State value);

	boolean validateTarget(State value);

	boolean validateLabel(Action value);

	boolean validateProbability(double value);
}
