/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.smodel.scoping;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.FilteringScope;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Action;
import org.palladiosimulator.simexp.dsl.smodel.smodel.ActionCall;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Parameter;
import org.palladiosimulator.simexp.dsl.smodel.smodel.ParameterValue;
import org.palladiosimulator.simexp.dsl.smodel.smodel.SmodelPackage;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping on how and when
 * to use it.
 */
public class SmodelScopeProvider extends AbstractSmodelScopeProvider {

    @Override
    public IScope getScope(EObject context, EReference reference) {
        IScope scope = super.getScope(context, reference);

        if (context instanceof ActionCall) {
            if (reference == SmodelPackage.Literals.ACTION_CALL__ACTION_REF) {
                return new FilteringScope(scope, action -> isBefore(action.getEObjectOrProxy(), context));
            }
        }

        if (context instanceof ParameterValue) {
            if (reference == SmodelPackage.Literals.PARAMETER_VALUE__PARAM_REF) {
                ActionCall actionCall = EcoreUtil2.getContainerOfType(context, ActionCall.class);
                Action action = actionCall.getActionRef();
                List<Parameter> parameters = EcoreUtil2.getAllContentsOfType(action, Parameter.class);
                return Scopes.scopeFor(parameters);
            }
        }

        return scope;
    }

    // Returns true iff 'objectA' was created before 'objectB'.
    private boolean isBefore(EObject objectA, EObject objectB) {
        // To avoid recursive definitions, if objectB is created within objectA, it is not
        // considered as created after objectA.
        if (EcoreUtil2.isAncestor(objectA, objectB)) {
            return false;
        }

        EObject root = EcoreUtil2.getRootContainer(objectA);
        List<EObject> contents = EcoreUtil2.eAllContentsAsList(root);

        // No need to check containment of objectA, as root is derived from it.
        if (contents.contains(objectB)) {
            int indexA = contents.indexOf(objectA);
            int indexB = contents.indexOf(objectB);
            return indexA < indexB;
        }

        return true;
    }
}
