/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.kmodel;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KmodelRuntimeModule extends AbstractKmodelRuntimeModule {
}
