/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.smodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SmodelUiModule extends AbstractSmodelUiModule {

    public SmodelUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
