/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.smodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Action;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Constant;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class SmodelOutlineTreeProvider extends DefaultOutlineTreeProvider {
    protected boolean _isLeaf(Constant ele) {
        return true;
    }

    protected boolean _isLeaf(Action ele) {
        return true;
    }
}
