/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.kmodel.validation;

import org.eclipse.xtext.validation.Check;
import java.util.Collections;
import java.util.List;
import java.util.NoSuchElementException;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtext.EcoreUtil2;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Action;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Addition;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.AdditiveInversion;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.BoolLiteral;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Comparison;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Conjunction;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Constant;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.DataType;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Equality;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Expression;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Field;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.FloatLiteral;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.IntLiteral;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.KModel;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.KmodelPackage;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Multiplication;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Negation;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Statement;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.StringLiteral;
import org.palladiosimulator.simexp.dsl.kmodel.kmodel.Variable;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class KmodelValidator extends AbstractKmodelValidator {
	
	@Check
	public void checkFieldDeclaredBeforeReference(Expression expression) {
		Field field = expression.getFieldRef();
		
		if (field != null && !fieldDeclaredBefore(field, expression)) {
			String name = field.getName();
			if (name != null) {
				error("Field '" + name + "' must be declared before referencing.",
						KmodelPackage.Literals.EXPRESSION__FIELD_REF);
			}
		}
	}
	
	@Check
	public void checkConstantForVariableValue(Constant constant) {
		Expression value = constant.getValue();
		
		if (containsVariable(value)) {
			error("Cannot assign an expression containing a variable to a constant value.",
					KmodelPackage.Literals.CONSTANT__VALUE);
		}
	}
	
	@Check
	public void checkConstantValueDataType(Constant constant) {
		Expression value = constant.getValue();
		
		if (value != null) {
			DataType constantDataType = constant.getDataType();
			DataType valueDataType = getDataType(value);
			
			if (!constantDataType.equals(valueDataType)) {
				if (constantDataType == DataType.FLOAT && valueDataType == DataType.INT) {
					return;
				}
				
				error("Expected a value of type '"
						+ constantDataType + "'. Got '" + valueDataType + "' instead.",
						KmodelPackage.Literals.CONSTANT__VALUE);
			}
		}
	}
	
	@Check
	public void checkConditionDataType(Statement statement) {
		Expression condition = statement.getCondition();
		
		if (condition != null) {
			DataType conditionType = getDataType(condition);
			
			if (!conditionType.equals(DataType.BOOL)) {
				error("The condition must be of type '" + DataType.BOOL 
						+ "'. Got '" + conditionType + "' instead.",
						KmodelPackage.Literals.STATEMENT__CONDITION);
			}
		}
	}
	
	@Check
	public void checkArgumentDataType(Statement statement) {
		Action action = statement.getActionRef();
		Expression argument = statement.getArgument();
		
		if (action != null && argument != null) {
			DataType parameterType = action.getParameter().getDataType();
			DataType argumentType = getDataType(argument);
			
			if (!parameterType.equals(argumentType)) {
				if (parameterType == DataType.FLOAT && argumentType == DataType.INT) {
					return;
				}
				
				error("Expected an argument of type '"
						+ parameterType + "'. Got '" + argumentType + "' instead.",
						KmodelPackage.Literals.STATEMENT__ARGUMENT);
			}
		}
	}
	
	@Check
	public void checkDisjunctionExpression(Expression disjunction) {
		if (!disjunction.getOp().equals("||")) {
			return;
		}
		
		DataType leftDataType = getDataType(disjunction.getLeft());
		DataType rightDataType = getDataType(disjunction.getRight());
		
		if (leftDataType != DataType.BOOL) {
			error("Expected a value of type '" + DataType.BOOL + "'. Got '" + leftDataType + "' instead.", 
					KmodelPackage.Literals.EXPRESSION__LEFT);
		}
		
		if (rightDataType != DataType.BOOL) {
			error("Expected a value of type '" + DataType.BOOL + "'. Got '" + rightDataType + "' instead.", 
					KmodelPackage.Literals.EXPRESSION__RIGHT);
		}
	}
	
	@Check
	public void checkConjunctionExpression(Conjunction conjunction) {
		if (!conjunction.getOp().equals("&&")) {
			return;
		}
		
		DataType leftDataType = getDataType(conjunction.getLeft());
		DataType rightDataType = getDataType(conjunction.getRight());
		
		if (leftDataType != DataType.BOOL) {
			error("Expected a value of type '" + DataType.BOOL + "'. Got '" + leftDataType + "' instead.", 
					KmodelPackage.Literals.EXPRESSION__LEFT);
		}
		
		if (rightDataType != DataType.BOOL) {
			error("Expected a value of type '" + DataType.BOOL + "'. Got '" + rightDataType + "' instead.", 
					KmodelPackage.Literals.EXPRESSION__RIGHT);
		}
	}
	
	@Check
	public void checkEqualityExpression(Equality equality) {
		if (!equality.getOp().equals("==") && !equality.getOp().equals("!=")) {
			return;
		}
		
		DataType leftDataType = getDataType(equality.getLeft());
		DataType rightDataType = getDataType(equality.getRight());
		
		boolean leftIsNumber = leftDataType == DataType.INT || leftDataType == DataType.FLOAT;
		boolean rightIsNumber = rightDataType == DataType.INT || rightDataType == DataType.FLOAT;
		
		if (!(leftIsNumber && rightIsNumber) && leftDataType != rightDataType) {
			error("Cannot compare the equality of a '"
					+ leftDataType + "' value with a '" + rightDataType + "' value.",
					KmodelPackage.Literals.EXPRESSION__LEFT);
			
			error("Cannot compare the equality of a '"
					+ leftDataType + "' value with a '" + rightDataType + "' value.",
					KmodelPackage.Literals.EXPRESSION__RIGHT);
		}
	}
	
	@Check
	public void checkNegationExpression(Negation negation) {
		if (!negation.getOp().equals("!")) {
			return;
		}
		
		DataType type = getDataType(negation.getLeft());
		
		if (type != DataType.BOOL) {
			error("Cannot negate a '" + type + "' value.",
					KmodelPackage.Literals.EXPRESSION__EXPR);
		}
	}
	
	@Check
	public void checkComparisonExpression(Comparison comparison) {
		if (!comparison.getOp().equals("<") && !comparison.getOp().equals("<=") 
				&& !comparison.getOp().equals(">=") && !comparison.getOp().equals(">")) {
			return;
		}
		
		DataType leftDataType = getDataType(comparison.getLeft());
		DataType rightDataType = getDataType(comparison.getRight());
		
		boolean leftIsNumber = leftDataType == DataType.INT || leftDataType == DataType.FLOAT;
		boolean rightIsNumber = rightDataType == DataType.INT || rightDataType == DataType.FLOAT;
		
		if (!leftIsNumber) {
			error("Cannot compare a '"
					+ leftDataType + "' value with a '" + rightDataType + "' value.",
					KmodelPackage.Literals.EXPRESSION__LEFT);
		}
		
		if (!rightIsNumber) {
			error("Cannot compare a '"
					+ leftDataType + "' value with a '" + rightDataType + "' value.",
					KmodelPackage.Literals.EXPRESSION__RIGHT);
		}
	}
	
	@Check
	public void checkAdditionExpression(Addition addition) {
		if (!addition.getOp().equals("+") && !addition.getOp().equals("-")) {
			return;
		}
		
		DataType leftDataType = getDataType(addition.getLeft());
		DataType rightDataType = getDataType(addition.getRight());
		
		boolean leftIsNumber = leftDataType == DataType.INT || leftDataType == DataType.FLOAT;
		boolean rightIsNumber = rightDataType == DataType.INT || rightDataType == DataType.FLOAT;
		
		if (!leftIsNumber) {
			error("Cannot add or subtract a '"
					+ leftDataType + "' value with a '" + rightDataType + "' value.",
					KmodelPackage.Literals.EXPRESSION__LEFT);
		}
		
		if (!rightIsNumber) {
			error("Cannot add or subtract a '"
					+ leftDataType + "' value with a '" + rightDataType + "' value.",
					KmodelPackage.Literals.EXPRESSION__RIGHT);
		}
	}
	
	@Check
	public void checkAdditiveInversionExpression(AdditiveInversion inversion) {
		if (!inversion.getOp().equals("-")) {
			return;
		}

		DataType type = getDataType(inversion.getLeft());
			
		if (type != DataType.INT && type != DataType.FLOAT) {
			error("Cannot invert a '" + type + "' value.",
					KmodelPackage.Literals.EXPRESSION__EXPR);
		}
	}
	
	@Check
	public void checkMultiplicationExpression(Multiplication multiplication) {
		if (!multiplication.getOp().equals("*") && !multiplication.getOp().equals("/")) {
			return;
		}
		
		DataType leftDataType = getDataType(multiplication.getLeft());
		DataType rightDataType = getDataType(multiplication.getRight());
		
		boolean leftIsNumber = leftDataType == DataType.INT || leftDataType == DataType.FLOAT;
		boolean rightIsNumber = rightDataType == DataType.INT || rightDataType == DataType.FLOAT;
		
		if (!leftIsNumber) {
			error("Cannot multiply or divide a '"
					+ leftDataType + "' value with a '" + rightDataType + "' value.",
					KmodelPackage.Literals.EXPRESSION__LEFT);
		}
		
		if (!rightIsNumber) {
			error("Cannot multiply or divide a '"
					+ leftDataType + "' value with a '" + rightDataType + "' value.",
					KmodelPackage.Literals.EXPRESSION__RIGHT);
		}
	}
	
	private DataType getDataType(Expression expression) {
		if (expression == null) {
			return null;
		}
		
		String operation = expression.getOp();
		
		if (operation != null) {
			switch (operation) {
			// Fallthrough, all cases are boolean.
			case "||":
			case "&&":
			case "==":
			case "!=":
			case "!":	
			case "<":
			case "<=":
			case ">=":
			case ">":	
				return DataType.BOOL;
			
			// Fallthrough, all cases are either int or float.
			case "+":
			case "-":
			case "*":
				DataType leftDataType = getDataType(expression.getLeft());
				DataType rightDataType = getDataType(expression.getRight());
				
				if (leftDataType == DataType.FLOAT || rightDataType == DataType.FLOAT) {
					return DataType.FLOAT;
				} else {
					return DataType.INT;
				}
				
			// Division returns always a float value.	
			case "/":
				return DataType.FLOAT;
				
			default: 
				break;	
			}
		}
		
		Expression left = expression.getLeft();
		if (left != null) {
			return getDataType(left);
		}
		
		Expression inner = expression.getExpr();
		if (inner != null) {
			return getDataType(inner);
		}
		
		Expression literal = expression.getLiteral();
		if (literal != null) {
			if (literal instanceof BoolLiteral) {
				return DataType.BOOL;
				
			} else if (literal instanceof IntLiteral) {
				return DataType.INT;
				
			} else if (literal instanceof FloatLiteral) {
				return DataType.FLOAT;
				
			} else if (literal instanceof StringLiteral) {
				return DataType.STRING;
			}
		}
		
		Field fieldRef = expression.getFieldRef();
		if (fieldRef != null) {
			return fieldRef.getDataType();
		}
		
		return null;
	}
	
	private boolean containsVariable(Expression expression) {
		if (expression == null) {
			return false;
		}
		
		Expression leftExpr = expression.getLeft();
		Expression rightExpr = expression.getRight();
		if (leftExpr != null) {
			if (rightExpr != null) {
				return containsVariable(leftExpr) || containsVariable(rightExpr);
			}
			
			return containsVariable(leftExpr);
		}
		
		Expression inner = expression.getExpr();
		if (inner != null) {
			return containsVariable(inner);
		}
		
		Field field = expression.getFieldRef();
		return field != null && field instanceof Variable;
	}
	
	private boolean fieldDeclaredBefore(Field field, Expression expression) {
		KModel kmodel = EcoreUtil2.getContainerOfType(expression, KModel.class);
		List<EObject> contents = EcoreUtil2.eAllContentsAsList(kmodel);
		List<EObject> fieldsDefinedBefore;
		
		try {
			EObject first = contents
					.stream()
					.filter(object -> EcoreUtil.isAncestor(object, expression))
					.findFirst()
					.get();
			fieldsDefinedBefore = contents.subList(0 , contents.indexOf(first));
		
		} catch (NoSuchElementException e) {
			fieldsDefinedBefore = Collections.emptyList();
		}
		
		return fieldsDefinedBefore.contains(field);
	}
}
