/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.kmodel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.palladiosimulator.simexp.dsl.kmodel.KmodelRuntimeModule;
import org.palladiosimulator.simexp.dsl.kmodel.KmodelStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class KmodelIdeSetup extends KmodelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new KmodelRuntimeModule(), new KmodelIdeModule()));
	}
	
}
