/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.smodel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.palladiosimulator.simexp.dsl.smodel.SmodelRuntimeModule;
import org.palladiosimulator.simexp.dsl.smodel.SmodelStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SmodelIdeSetup extends SmodelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SmodelRuntimeModule(), new SmodelIdeModule()));
	}
	
}
