/*
 * generated by Xtext 2.26.0
 */
package org.palladiosimulator.simexp.dsl.smodel.ui.labeling;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.StringUtils;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Action;
import org.palladiosimulator.simexp.dsl.smodel.smodel.ActionArguments;
import org.palladiosimulator.simexp.dsl.smodel.smodel.ActionCall;
import org.palladiosimulator.simexp.dsl.smodel.smodel.BoolLiteral;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Bounds;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Constant;
import org.palladiosimulator.simexp.dsl.smodel.smodel.DataType;
import org.palladiosimulator.simexp.dsl.smodel.smodel.DoubleLiteral;
import org.palladiosimulator.simexp.dsl.smodel.smodel.EnvVariable;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Expression;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Field;
import org.palladiosimulator.simexp.dsl.smodel.smodel.IfStatement;
import org.palladiosimulator.simexp.dsl.smodel.smodel.IntLiteral;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Operation;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Optimizable;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Parameter;
import org.palladiosimulator.simexp.dsl.smodel.smodel.ParameterValue;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Probe;
import org.palladiosimulator.simexp.dsl.smodel.smodel.ProbeAdressingKind;
import org.palladiosimulator.simexp.dsl.smodel.smodel.RangeBounds;
import org.palladiosimulator.simexp.dsl.smodel.smodel.SetBounds;
import org.palladiosimulator.simexp.dsl.smodel.smodel.StringLiteral;
import org.palladiosimulator.simexp.dsl.smodel.smodel.Variable;

import com.google.inject.Inject;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class SmodelLabelProvider extends DefaultEObjectLabelProvider {

    @Inject
    public SmodelLabelProvider(AdapterFactoryLabelProvider delegate) {
        super(delegate);
    }

    public String text(Constant constant) {
        StringBuilder sb = new StringBuilder();
        sb.append(toTextField(constant));
        Expression value = constant.getValue();
        if (value != null) {
            sb.append(" = ");
            sb.append(getText(value));
        }
        return sb.toString();
    }

    public String text(Variable variable) {
        StringBuilder sb = new StringBuilder();
        sb.append(toTextField(variable));
        Expression value = variable.getValue();
        if (value != null) {
            sb.append(" = ");
            sb.append(getText(value));
        }
        return sb.toString();
    }

    public String text(EnvVariable envVariable) {
        StringBuilder sb = new StringBuilder();
        sb.append(toTextField(envVariable));
        String variableId = envVariable.getVariableId();
        sb.append(" ");
        sb.append("variableId");
        sb.append("=");
        sb.append(variableId);
        return sb.toString();
    }

    public String text(Probe probe) {
        StringBuilder sb = new StringBuilder();
        sb.append(toTextField(probe));
        ProbeAdressingKind kind = probe.getKind();
        sb.append(" ");
        sb.append(kind.getLiteral());
        sb.append("=");
        sb.append(probe.getIdentifier());
        return sb.toString();
    }

    public String text(Optimizable optimizable) {
        StringBuilder sb = new StringBuilder();
        sb.append(toTextField(optimizable));
        Bounds bounds = optimizable.getValues();
        if (bounds != null) {
            sb.append(" ");
            sb.append(getText(bounds));
        }
        return sb.toString();
    }

    private String toTextField(Field field) {
        StringBuilder sb = new StringBuilder();
        sb.append(field.eClass()
            .getName());
        sb.append(" ");
        sb.append(field.getName());

        DataType dataType = field.getDataType();
        sb.append(" ");
        sb.append(dataType.getLiteral());

        return sb.toString();
    }

    public String text(SetBounds bounds) {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        List<String> entries = new ArrayList<>();
        for (Expression value : bounds.getValues()) {
            entries.add(getText(value));
        }
        sb.append(StringUtils.join(entries, ", "));
        sb.append("}");
        return sb.toString();
    }

    public String text(RangeBounds bounds) {
        StringBuilder sb = new StringBuilder();
        sb.append("[start=");
        Expression startValue = bounds.getStartValue();
        if (startValue != null) {
            sb.append(getText(startValue));
        }
        sb.append(", end=");
        Expression endValue = bounds.getEndValue();
        if (endValue != null) {
            sb.append(getText(endValue));
        }
        sb.append(", step=");
        Expression stepSize = bounds.getStepSize();
        if (stepSize != null) {
            sb.append(getText(stepSize));
        }
        sb.append("]");
        return sb.toString();
    }

    public String text(Action action) {
        StringBuilder sb = new StringBuilder();
        sb.append("Action ");
        sb.append(action.getName());
        sb.append("(");
        ActionArguments arguments = action.getArguments();
        if (arguments != null) {
            List<String> paramEntries = new ArrayList<>();
            List<Parameter> parameters = arguments.getParameters();
            for (Parameter parameter : parameters) {
                if (parameter != null) {
                    DataType dataType = parameter.getDataType();
                    paramEntries.add(dataType.getLiteral());
                }
            }
            sb.append(StringUtils.join(paramEntries, ", "));

            List<Optimizable> optimizables = arguments.getOptimizables();
            if (!(parameters.isEmpty() && optimizables.isEmpty())) {
                sb.append(" | ");
                List<String> optimizableEntries = new ArrayList<>();

                for (Optimizable optimizable : optimizables) {
                    if (optimizable != null) {
                        DataType dataType = optimizable.getDataType();
                        optimizableEntries.add(dataType.getLiteral());
                    }
                }
                sb.append(StringUtils.join(optimizableEntries, ", "));
            }
        }
        sb.append(")");
        return sb.toString();
    }

    public String text(ActionCall actionCall) {
        StringBuilder sb = new StringBuilder();
        Action actionRef = actionCall.getActionRef();
        sb.append("ActionCall ");
        if (actionRef != null) {
            sb.append(actionRef.getName());
        }
        sb.append("(");
        List<String> entries = new ArrayList<>();
        List<ParameterValue> arguments = actionCall.getArguments();
        for (ParameterValue parameterValue : arguments) {
            Parameter paramRef = parameterValue.getParamRef();
            String value = getText(parameterValue.getArgument());
            entries.add(String.format("%s=%s", paramRef.getName(), value));
        }
        sb.append(StringUtils.join(entries, ", "));
        sb.append(")");
        return sb.toString();
    }

    public String text(IfStatement ifStatement) {
        StringBuilder sb = new StringBuilder();
        sb.append("if ");
        sb.append("(");
        Expression condition = ifStatement.getCondition();
        if (condition != null) {
            sb.append(getText(condition));
        }
        sb.append(")");
        return sb.toString();
    }

    public String text(Expression expression) {
        Field fieldRef = expression.getFieldRef();
        if (fieldRef != null) {
            return getText(fieldRef);
        }
        Expression literal = expression.getLiteral();
        if (literal != null) {
            return getText(literal);
        }

        Operation operation = expression.getOp();
        Expression left = expression.getLeft();
        switch (operation) {
        case UNDEFINED: {
            if (left != null) {
                return getText(left);
            }
            return "";
        }

        case NOT:
            if (left != null) {
                return getText(left);
            }
            return "";

        default:
            StringBuilder sb = new StringBuilder();
            sb.append(getText(left));
            sb.append(" ");
            sb.append(operation.getLiteral());
            sb.append(" ");

            Expression right = expression.getRight();
            if (right != null) {
                sb.append(getText(right));
            }
            return sb.toString();
        }
    }

    public String text(IntLiteral literal) {
        return Integer.toString(literal.getValue());
    }

    public String text(DoubleLiteral literal) {
        return Double.toString(literal.getValue());
    }

    public String text(BoolLiteral literal) {
        return Boolean.toString(literal.isTrue());
    }

    public String text(StringLiteral literal) {
        return literal.getValue();
    }
}
